#mock config here.

logging:
  level:
    com.portfolio.elite: DEBUG


elite:
  logging:
    config:
      correlation:
        enabled: true
        header-name: X-Correlation-ID
        mdc-enabled: true