server:
  port: 9010

spring:
  application:
    name: customer-service

  config:
    import: configserver:http://localhost:8888

#observability configurations
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh


profiles:
  name: profile-service
  url: http://localhost:9091

elite:
  logging:
    config:
      correlation:
        enabled: true
        header-name: X-Correlation-ID
        mdc-enabled: true