server:
  port: 9091

spring:
  application:
    name: profile-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

elite:
  logging:
    config:
      correlation:
        enabled: true
        header-name: X-Correlation-ID
        mdc-enabled: true
